// 2014 SRD equipment: the name and the price. No descriptive text.
// Bundle prices are for the quantity in the name. Barding is four times the armor.

export const COUNTER_CAP = 60;

export const BASE_LIST = [
  {
    id: "weapons",
    name: "Weapons",
    items: [
      { id: "club", name: "Club", cp: 10 },
      { id: "dagger", name: "Dagger", cp: 200 },
      { id: "greatclub", name: "Greatclub", cp: 20 },
      { id: "handaxe", name: "Handaxe", cp: 500 },
      { id: "javelin", name: "Javelin", cp: 50 },
      { id: "light-hammer", name: "Light hammer", cp: 200 },
      { id: "mace", name: "Mace", cp: 500 },
      { id: "quarterstaff", name: "Quarterstaff", cp: 20 },
      { id: "sickle", name: "Sickle", cp: 100 },
      { id: "spear", name: "Spear", cp: 100 },
      { id: "light-crossbow", name: "Light crossbow", cp: 2500 },
      { id: "dart", name: "Dart", cp: 5 },
      { id: "shortbow", name: "Shortbow", cp: 2500 },
      { id: "sling", name: "Sling", cp: 10 },
      { id: "battleaxe", name: "Battleaxe", cp: 1000 },
      { id: "flail", name: "Flail", cp: 1000 },
      { id: "glaive", name: "Glaive", cp: 2000 },
      { id: "greataxe", name: "Greataxe", cp: 3000 },
      { id: "greatsword", name: "Greatsword", cp: 5000 },
      { id: "halberd", name: "Halberd", cp: 2000 },
      { id: "lance", name: "Lance", cp: 1000 },
      { id: "longsword", name: "Longsword", cp: 1500 },
      { id: "maul", name: "Maul", cp: 1000 },
      { id: "morningstar", name: "Morningstar", cp: 1500 },
      { id: "pike", name: "Pike", cp: 500 },
      { id: "rapier", name: "Rapier", cp: 2500 },
      { id: "scimitar", name: "Scimitar", cp: 2500 },
      { id: "shortsword", name: "Shortsword", cp: 1000 },
      { id: "trident", name: "Trident", cp: 500 },
      { id: "war-pick", name: "War pick", cp: 500 },
      { id: "warhammer", name: "Warhammer", cp: 1500 },
      { id: "whip", name: "Whip", cp: 200 },
      { id: "blowgun", name: "Blowgun", cp: 1000 },
      { id: "hand-crossbow", name: "Hand crossbow", cp: 7500 },
      { id: "heavy-crossbow", name: "Heavy crossbow", cp: 5000 },
      { id: "longbow", name: "Longbow", cp: 5000 },
      { id: "net", name: "Net", cp: 100 },
    ],
  },
  {
    id: "armor",
    name: "Armor",
    items: [
      { id: "padded", name: "Padded armor", cp: 500 },
      { id: "leather", name: "Leather armor", cp: 1000 },
      { id: "studded-leather", name: "Studded leather", cp: 4500 },
      { id: "hide", name: "Hide armor", cp: 1000 },
      { id: "chain-shirt", name: "Chain shirt", cp: 5000 },
      { id: "scale-mail", name: "Scale mail", cp: 5000 },
      { id: "breastplate", name: "Breastplate", cp: 40000 },
      { id: "half-plate", name: "Half plate", cp: 75000 },
      { id: "ring-mail", name: "Ring mail", cp: 3000 },
      { id: "chain-mail", name: "Chain mail", cp: 7500 },
      { id: "splint", name: "Splint armor", cp: 20000 },
      { id: "plate-armor", name: "Plate armor", cp: 150000 },
      { id: "shield", name: "Shield", cp: 1000 },
    ],
  },
  {
    id: "ammunition",
    name: "Ammunition",
    items: [
      { id: "arrows", name: "Arrows (20)", cp: 100 },
      { id: "bolts", name: "Crossbow bolts (20)", cp: 100 },
      { id: "blowgun-needles", name: "Blowgun needles (50)", cp: 100 },
      { id: "sling-bullets", name: "Sling bullets (20)", cp: 4 },
    ],
  },
  {
    id: "gear",
    name: "Adventuring gear",
    items: [
      { id: "abacus", name: "Abacus", cp: 200 },
      { id: "acid", name: "Acid (vial)", cp: 2500, consumable: true },
      { id: "alchemists-fire", name: "Alchemist's fire", cp: 5000, consumable: true },
      { id: "antitoxin", name: "Antitoxin", cp: 5000, consumable: true },
      { id: "backpack", name: "Backpack", cp: 200 },
      { id: "ball-bearings", name: "Ball bearings (bag of 1,000)", cp: 100 },
      { id: "barrel", name: "Barrel", cp: 200 },
      { id: "basket", name: "Basket", cp: 40 },
      { id: "bedroll", name: "Bedroll", cp: 100 },
      { id: "bell", name: "Bell", cp: 100 },
      { id: "blanket", name: "Blanket", cp: 50 },
      { id: "block-and-tackle", name: "Block and tackle", cp: 100 },
      { id: "book", name: "Book", cp: 2500 },
      { id: "bottle", name: "Bottle, glass", cp: 200 },
      { id: "bucket", name: "Bucket", cp: 5 },
      { id: "caltrops", name: "Caltrops (bag of 20)", cp: 100 },
      { id: "candle", name: "Candle", cp: 1, consumable: true },
      { id: "bolt-case", name: "Case, crossbow bolt", cp: 100 },
      { id: "scroll-case", name: "Case, map or scroll", cp: 100 },
      { id: "chain", name: "Chain (10 feet)", cp: 500 },
      { id: "chalk", name: "Chalk (1 piece)", cp: 1, consumable: true },
      { id: "chest", name: "Chest", cp: 500 },
      { id: "climbers-kit", name: "Climber's kit", cp: 2500 },
      { id: "clothes", name: "Common clothes", cp: 50 },
      { id: "clothes-costume", name: "Costume clothes", cp: 500 },
      { id: "clothes-fine", name: "Fine clothes", cp: 1500 },
      { id: "clothes-travelers", name: "Traveler's clothes", cp: 200 },
      { id: "component-pouch", name: "Component pouch", cp: 2500 },
      { id: "crowbar", name: "Crowbar", cp: 200 },
      { id: "fishing-tackle", name: "Fishing tackle", cp: 100 },
      { id: "flask", name: "Flask or tankard", cp: 2 },
      { id: "grappling-hook", name: "Grappling hook", cp: 200 },
      { id: "hammer", name: "Hammer", cp: 100 },
      { id: "sledge", name: "Hammer, sledge", cp: 200 },
      { id: "holy-water", name: "Holy water", cp: 2500, consumable: true },
      { id: "hourglass", name: "Hourglass", cp: 2500 },
      { id: "hunting-trap", name: "Hunting trap", cp: 500 },
      { id: "ink", name: "Ink (1 ounce)", cp: 1000 },
      { id: "ink-pen", name: "Ink pen", cp: 2 },
      { id: "jug", name: "Jug or pitcher", cp: 2 },
      { id: "ladder", name: "Ladder (10-foot)", cp: 10 },
      { id: "lamp", name: "Lamp", cp: 50 },
      { id: "lantern-bullseye", name: "Lantern, bullseye", cp: 1000 },
      { id: "lantern-hooded", name: "Lantern, hooded", cp: 500 },
      { id: "lock", name: "Lock", cp: 1000 },
      { id: "magnifying-glass", name: "Magnifying glass", cp: 10000 },
      { id: "manacles", name: "Manacles", cp: 200 },
      { id: "mess-kit", name: "Mess kit", cp: 20 },
      { id: "mirror", name: "Mirror, steel", cp: 500 },
      { id: "oil", name: "Oil (flask)", cp: 10, consumable: true },
      { id: "paper", name: "Paper (one sheet)", cp: 20 },
      { id: "parchment", name: "Parchment (one sheet)", cp: 10 },
      { id: "perfume", name: "Perfume (vial)", cp: 500 },
      { id: "miners-pick", name: "Pick, miner's", cp: 200 },
      { id: "piton", name: "Piton", cp: 5 },
      { id: "poison-basic", name: "Poison, basic (vial)", cp: 10000, consumable: true },
      { id: "pole", name: "Pole (10-foot)", cp: 5 },
      { id: "iron-pot", name: "Pot, iron", cp: 200 },
      { id: "potion-healing", name: "Potion of healing", cp: 5000, consumable: true },
      { id: "pouch", name: "Pouch", cp: 50 },
      { id: "quiver", name: "Quiver", cp: 100 },
      { id: "portable-ram", name: "Ram, portable", cp: 400 },
      { id: "rations", name: "Rations (1 day)", cp: 50, consumable: true },
      { id: "robes", name: "Robes", cp: 100 },
      { id: "rope", name: "Hempen rope, 50 feet", cp: 100 },
      { id: "rope-silk", name: "Silk rope, 50 feet", cp: 1000 },
      { id: "sack", name: "Sack", cp: 1 },
      { id: "merchants-scale", name: "Scale, merchant's", cp: 500 },
      { id: "sealing-wax", name: "Sealing wax", cp: 50 },
      { id: "shovel", name: "Shovel", cp: 200 },
      { id: "signal-whistle", name: "Signal whistle", cp: 5 },
      { id: "signet-ring", name: "Signet ring", cp: 500 },
      { id: "soap", name: "Soap", cp: 2 },
      { id: "spellbook", name: "Spellbook", cp: 5000 },
      { id: "iron-spikes", name: "Spikes, iron (10)", cp: 100 },
      { id: "spyglass", name: "Spyglass", cp: 100000 },
      { id: "tent", name: "Tent, two-person", cp: 200 },
      { id: "tinderbox", name: "Tinderbox", cp: 50 },
      { id: "torch", name: "Torch", cp: 1, consumable: true },
      { id: "vial", name: "Vial", cp: 100 },
      { id: "waterskin", name: "Waterskin", cp: 20 },
      { id: "whetstone", name: "Whetstone", cp: 1 },
      { id: "holy-symbol", name: "Holy symbol", cp: 500 },
      { id: "amulet", name: "Holy symbol, amulet", cp: 500 },
      { id: "emblem", name: "Holy symbol, emblem", cp: 500 },
      { id: "reliquary", name: "Holy symbol, reliquary", cp: 500 },
      { id: "arcane-focus", name: "Arcane focus", cp: 1000 },
      { id: "crystal", name: "Arcane focus, crystal", cp: 1000 },
      { id: "orb", name: "Arcane focus, orb", cp: 2000 },
      { id: "rod", name: "Arcane focus, rod", cp: 1000 },
      { id: "arcane-staff", name: "Arcane focus, staff", cp: 500 },
      { id: "wand", name: "Arcane focus, wand", cp: 1000 },
      { id: "druidic-focus", name: "Druidic focus", cp: 100 },
      { id: "mistletoe", name: "Druidic focus, mistletoe", cp: 100 },
      { id: "totem", name: "Druidic focus, totem", cp: 100 },
      { id: "wooden-staff", name: "Druidic focus, wooden staff", cp: 500 },
      { id: "yew-wand", name: "Druidic focus, yew wand", cp: 1000 },
      { id: "burglars-pack", name: "Burglar's pack", cp: 1600 },
      { id: "diplomats-pack", name: "Diplomat's pack", cp: 3900 },
      { id: "dungeoneers-pack", name: "Dungeoneer's pack", cp: 1200 },
      { id: "entertainers-pack", name: "Entertainer's pack", cp: 4000 },
      { id: "explorers-pack", name: "Explorer's pack", cp: 1000 },
      { id: "priests-pack", name: "Priest's pack", cp: 1900 },
      { id: "scholars-pack", name: "Scholar's pack", cp: 4000 },
    ],
  },
  {
    id: "tools",
    name: "Tools",
    items: [
      { id: "alchemists-supplies", name: "Alchemist's supplies", cp: 5000 },
      { id: "brewers-supplies", name: "Brewer's supplies", cp: 2000 },
      { id: "calligraphers-supplies", name: "Calligrapher's supplies", cp: 1000 },
      { id: "carpenters-tools", name: "Carpenter's tools", cp: 800 },
      { id: "cartographers-tools", name: "Cartographer's tools", cp: 1500 },
      { id: "cobblers-tools", name: "Cobbler's tools", cp: 500 },
      { id: "cooks-utensils", name: "Cook's utensils", cp: 100 },
      { id: "glassblowers-tools", name: "Glassblower's tools", cp: 3000 },
      { id: "jewelers-tools", name: "Jeweler's tools", cp: 2500 },
      { id: "leatherworkers-tools", name: "Leatherworker's tools", cp: 500 },
      { id: "masons-tools", name: "Mason's tools", cp: 1000 },
      { id: "painters-supplies", name: "Painter's supplies", cp: 1000 },
      { id: "potters-tools", name: "Potter's tools", cp: 1000 },
      { id: "smiths-tools", name: "Smith's tools", cp: 2000 },
      { id: "tinkers-tools", name: "Tinker's tools", cp: 5000 },
      { id: "weavers-tools", name: "Weaver's tools", cp: 100 },
      { id: "woodcarvers-tools", name: "Woodcarver's tools", cp: 100 },
      { id: "disguise-kit", name: "Disguise kit", cp: 2500 },
      { id: "forgery-kit", name: "Forgery kit", cp: 1500 },
      { id: "herbalism-kit", name: "Herbalism kit", cp: 500 },
      { id: "healers-kit", name: "Healer's kit", cp: 500 },
      { id: "navigators-tools", name: "Navigator's tools", cp: 2500 },
      { id: "poisoners-kit", name: "Poisoner's kit", cp: 5000 },
      { id: "thieves-tools", name: "Thieves' tools", cp: 2500 },
      { id: "dice-set", name: "Dice set", cp: 10 },
      { id: "playing-cards", name: "Playing card set", cp: 50 },
      { id: "bagpipes", name: "Bagpipes", cp: 3000 },
      { id: "drum", name: "Drum", cp: 600 },
      { id: "dulcimer", name: "Dulcimer", cp: 2500 },
      { id: "flute", name: "Flute", cp: 200 },
      { id: "lute", name: "Lute", cp: 3500 },
      { id: "lyre", name: "Lyre", cp: 3000 },
      { id: "horn", name: "Horn", cp: 300 },
      { id: "pan-flute", name: "Pan flute", cp: 1200 },
      { id: "shawm", name: "Shawm", cp: 200 },
      { id: "viol", name: "Viol", cp: 3000 },
    ],
  },
  {
    id: "mounts",
    name: "Mounts and vehicles",
    items: [
      { id: "camel", name: "Camel", cp: 5000 },
      { id: "donkey", name: "Donkey", cp: 800 },
      { id: "mule", name: "Mule", cp: 800 },
      { id: "elephant", name: "Elephant", cp: 20000 },
      { id: "draft-horse", name: "Draft horse", cp: 5000 },
      { id: "riding-horse", name: "Riding horse", cp: 7500 },
      { id: "mastiff", name: "Mastiff", cp: 2500 },
      { id: "pony", name: "Pony", cp: 3000 },
      { id: "warhorse", name: "Warhorse", cp: 40000 },
      { id: "barding-padded", name: "Barding, padded", cp: 2000 },
      { id: "barding-leather", name: "Barding, leather", cp: 4000 },
      { id: "barding-studded", name: "Barding, studded leather", cp: 18000 },
      { id: "barding-hide", name: "Barding, hide", cp: 4000 },
      { id: "barding-chain-shirt", name: "Barding, chain shirt", cp: 20000 },
      { id: "barding-scale", name: "Barding, scale mail", cp: 20000 },
      { id: "barding-breastplate", name: "Barding, breastplate", cp: 160000 },
      { id: "barding-half-plate", name: "Barding, half plate", cp: 300000 },
      { id: "barding-ring", name: "Barding, ring mail", cp: 12000 },
      { id: "barding-chain-mail", name: "Barding, chain mail", cp: 30000 },
      { id: "barding-splint", name: "Barding, splint", cp: 80000 },
      { id: "barding-plate", name: "Barding, plate", cp: 600000 },
      { id: "bit-and-bridle", name: "Bit and bridle", cp: 200 },
      { id: "saddle-exotic", name: "Saddle, exotic", cp: 6000 },
      { id: "saddle-military", name: "Saddle, military", cp: 2000 },
      { id: "saddle-pack", name: "Saddle, pack", cp: 500 },
      { id: "saddle-riding", name: "Saddle, riding", cp: 1000 },
      { id: "saddlebags", name: "Saddlebags", cp: 400 },
      { id: "carriage", name: "Carriage", cp: 10000 },
      { id: "cart", name: "Cart", cp: 1500 },
      { id: "chariot", name: "Chariot", cp: 25000 },
      { id: "sled", name: "Sled", cp: 2000 },
      { id: "wagon", name: "Wagon", cp: 3500 },
      { id: "rowboat", name: "Rowboat", cp: 5000 },
      { id: "keelboat", name: "Keelboat", cp: 300000 },
      { id: "longship", name: "Longship", cp: 1000000 },
      { id: "sailing-ship", name: "Sailing ship", cp: 1000000 },
      { id: "galley", name: "Galley", cp: 3000000 },
      { id: "warship", name: "Warship", cp: 2500000 },
      { id: "animal-feed", name: "Animal feed (1 day)", cp: 5, service: true },
      { id: "stabling", name: "Stabling (1 day)", cp: 50, service: true },
    ],
  },
  {
    id: "trade",
    name: "Trade goods",
    items: [
      { id: "wheat", name: "Wheat (1 lb.)", cp: 1 },
      { id: "flour", name: "Flour (1 lb.)", cp: 2 },
      { id: "chicken", name: "Chicken", cp: 2 },
      { id: "salt", name: "Salt (1 lb.)", cp: 5 },
      { id: "iron-lb", name: "Iron (1 lb.)", cp: 10 },
      { id: "canvas", name: "Canvas (1 sq. yd.)", cp: 10 },
      { id: "copper-lb", name: "Copper (1 lb.)", cp: 50 },
      { id: "cotton", name: "Cotton cloth (1 sq. yd.)", cp: 50 },
      { id: "ginger", name: "Ginger (1 lb.)", cp: 100 },
      { id: "goat", name: "Goat", cp: 100 },
      { id: "cinnamon", name: "Cinnamon (1 lb.)", cp: 200 },
      { id: "pepper", name: "Pepper (1 lb.)", cp: 200 },
      { id: "sheep", name: "Sheep", cp: 200 },
      { id: "cloves", name: "Cloves (1 lb.)", cp: 300 },
      { id: "pig", name: "Pig", cp: 300 },
      { id: "silver-lb", name: "Silver (1 lb.)", cp: 500 },
      { id: "linen", name: "Linen (1 sq. yd.)", cp: 500 },
      { id: "silk", name: "Silk (1 sq. yd.)", cp: 1000 },
      { id: "cow", name: "Cow", cp: 1000 },
      { id: "saffron", name: "Saffron (1 lb.)", cp: 1500 },
      { id: "ox", name: "Ox", cp: 1500 },
      { id: "gold-lb", name: "Gold (1 lb.)", cp: 5000 },
      { id: "platinum-lb", name: "Platinum (1 lb.)", cp: 50000 },
    ],
  },
  {
    id: "tavern",
    name: "Food, drink, and lodging",
    items: [
      { id: "ale-gallon", name: "Ale, gallon", cp: 20, service: true },
      { id: "ale-mug", name: "Ale, mug", cp: 4, service: true },
      { id: "banquet", name: "Banquet (per person)", cp: 1000, service: true },
      { id: "bread", name: "Bread, loaf", cp: 2, service: true },
      { id: "cheese", name: "Cheese, hunk", cp: 10, service: true },
      { id: "meat", name: "Meat, chunk", cp: 30, service: true },
      { id: "wine-common", name: "Wine, common (pitcher)", cp: 20, service: true },
      { id: "wine-fine", name: "Wine, fine (bottle)", cp: 1000, service: true },
      { id: "meal-squalid", name: "Meal, squalid", cp: 3, service: true },
      { id: "meal-poor", name: "Meal, poor", cp: 6, service: true },
      { id: "meal-modest", name: "Meal, modest", cp: 30, service: true },
      { id: "meal-comfortable", name: "Meal, comfortable", cp: 50, service: true },
      { id: "meal-wealthy", name: "Meal, wealthy", cp: 80, service: true },
      { id: "meal-aristocratic", name: "Meal, aristocratic", cp: 200, service: true },
      { id: "room-squalid", name: "Room for the night, squalid", cp: 7, service: true },
      { id: "room-poor", name: "Room for the night, poor", cp: 10, service: true },
      { id: "room-modest", name: "Room for the night, modest", cp: 50, service: true },
      { id: "room-comfortable", name: "Room for the night, comfortable", cp: 80, service: true },
      { id: "room-wealthy", name: "Room for the night, wealthy", cp: 200, service: true },
      { id: "room-aristocratic", name: "Room for the night, aristocratic", cp: 400, service: true },
    ],
  },
];
